CREATE DATABASE IF NOT EXISTS clientedb; CREATE DATABASE IF NOT EXISTS cuentadb;
--
-- Name: persona; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persona (
    tipo_persona character varying(31) NOT NULL,
    id_persona bigint NOT NULL,
    direccion_persona character varying(200),
    edad_persona integer,
    fecha_creacion timestamp(6) without time zone,
    genero_persona character varying(20),
    nombre_persona character varying(100) NOT NULL,
    telefono_persona character varying(20),
    contrasena_cliente character varying(100) NOT NULL,
    estado_cliente boolean NOT NULL,
    id_cliente bigint NOT NULL,
    CONSTRAINT persona_tipo_persona_check CHECK (((tipo_persona)::text = 'CLIENTE'::text))
);


--
-- Name: persona_id_persona_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.persona ALTER COLUMN id_persona ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_persona_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id_persona);


--
-- Name: persona ukco2oot0f2xrpo0utwqks8ql6k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT ukco2oot0f2xrpo0utwqks8ql6k UNIQUE (id_cliente);

--
-- Name: cuentas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cuentas (
    id_cuenta bigint NOT NULL,
    estado_cuenta boolean NOT NULL,
    id_cliente bigint NOT NULL,
    nombre_cliente character varying(100),
    numero_cuenta bigint NOT NULL,
    saldo_actual numeric(15,2) NOT NULL,
    saldo_inicial numeric(15,2) NOT NULL,
    tipo_cuenta character varying(20) NOT NULL
);


--
-- Name: cuentas_id_cuenta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cuentas ALTER COLUMN id_cuenta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuentas_id_cuenta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimientos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movimientos (
    id_movimiento bigint NOT NULL,
    estado_movimiento boolean NOT NULL,
    fecha_movimiento timestamp(6) without time zone NOT NULL,
    saldo numeric(14,2),
    tipo_movimiento character varying(255) NOT NULL,
    valor numeric(15,2),
    cuenta_id bigint NOT NULL,
    CONSTRAINT movimientos_tipo_movimiento_check CHECK (((tipo_movimiento)::text = ANY ((ARRAY['DEPOSITO'::character varying, 'RETIRO'::character varying, 'REVERSA'::character varying])::text[])))
);


--
-- Name: movimientos_id_movimiento_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movimientos ALTER COLUMN id_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_id_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuentas cuentas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT cuentas_pkey PRIMARY KEY (id_cuenta);


--
-- Name: movimientos movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_pkey PRIMARY KEY (id_movimiento);


--
-- Name: cuentas uk7h7mqvcau3mcl0mbrkdrt7fnh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT uk7h7mqvcau3mcl0mbrkdrt7fnh UNIQUE (numero_cuenta);


--
-- Name: movimientos fk4moe88hxuohcysas5h70mdc09; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT fk4moe88hxuohcysas5h70mdc09 FOREIGN KEY (cuenta_id) REFERENCES public.cuentas(id_cuenta);
