--
-- PostgreSQL database dump
--

\restrict 383sne1XNwmjm5nYY7IhWqbhgYbLuoKmofatjYmLXasi3EGxcDyHDPk0pBmanXD

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2026-01-30 13:38:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 33083)
-- Name: persona; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persona (
    tipo_persona character varying(31) NOT NULL,
    id_persona bigint NOT NULL,
    direccion_persona character varying(200),
    edad_persona integer,
    fecha_creacion timestamp(6) without time zone,
    genero_persona character varying(20),
    identificacion_persona character varying(20) NOT NULL,
    nombre_persona character varying(100) NOT NULL,
    telefono_persona character varying(20),
    contrasena_cliente character varying(100) NOT NULL,
    estado_cliente character varying(20) NOT NULL,
    id_cliente character varying(50) NOT NULL,
    CONSTRAINT persona_estado_cliente_check CHECK (((estado_cliente)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying, 'BLOQUEDADO'::character varying])::text[]))),
    CONSTRAINT persona_tipo_persona_check CHECK (((tipo_persona)::text = 'CLIENTE'::text))
);


ALTER TABLE public.persona OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 33082)
-- Name: persona_id_persona_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.persona ALTER COLUMN id_persona ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_persona_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4911 (class 0 OID 33083)
-- Dependencies: 220
-- Data for Name: persona; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.persona (tipo_persona, id_persona, direccion_persona, edad_persona, fecha_creacion, genero_persona, identificacion_persona, nombre_persona, telefono_persona, contrasena_cliente, estado_cliente, id_cliente) FROM stdin;
\.


--
-- TOC entry 4917 (class 0 OID 0)
-- Dependencies: 219
-- Name: persona_id_persona_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.persona_id_persona_seq', 1, false);


--
-- TOC entry 4758 (class 2606 OID 33098)
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id_persona);


--
-- TOC entry 4760 (class 2606 OID 33102)
-- Name: persona ukco2oot0f2xrpo0utwqks8ql6k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT ukco2oot0f2xrpo0utwqks8ql6k UNIQUE (id_cliente);


--
-- TOC entry 4762 (class 2606 OID 33100)
-- Name: persona ukgd31rvxpqrlrgkla5gfl1gfhr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT ukgd31rvxpqrlrgkla5gfl1gfhr UNIQUE (identificacion_persona);


-- Completed on 2026-01-30 13:38:54

--
-- PostgreSQL database dump complete
--

\unrestrict 383sne1XNwmjm5nYY7IhWqbhgYbLuoKmofatjYmLXasi3EGxcDyHDPk0pBmanXD

