--
-- PostgreSQL database dump
--

\restrict Di57OhKhQslh7jJBslK0HgA7ZZHui2rigRbzZqW5N0jbewtEyZfp63RrorpF6jW

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2026-01-30 13:40:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 33104)
-- Name: cuentas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuentas (
    saldo_actual numeric(15,2) NOT NULL,
    saldo_inicial numeric(15,2) NOT NULL,
    id_cliente bigint NOT NULL,
    id_cuenta bigint NOT NULL,
    numero_cuenta character varying(20) NOT NULL,
    tipo_cuenta character varying(20) NOT NULL,
    nombre_cliente character varying(100),
    estado_cuenta character varying(255) NOT NULL,
    CONSTRAINT cuentas_estado_cuenta_check CHECK (((estado_cuenta)::text = ANY ((ARRAY['ACTIVA'::character varying, 'INACTIVA'::character varying, 'BLOQUEADA'::character varying])::text[])))
);


ALTER TABLE public.cuentas OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 33103)
-- Name: cuentas_id_cuenta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuentas ALTER COLUMN id_cuenta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuentas_id_cuenta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 33120)
-- Name: movimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimientos (
    saldo numeric(15,2),
    valor numeric(15,2),
    cuenta_id bigint NOT NULL,
    fecha_movimiento timestamp(6) without time zone NOT NULL,
    id_cliente bigint,
    id_movimiento bigint NOT NULL,
    tipo_movimiento character varying(20) NOT NULL,
    nombre_cliente character varying(100)
);


ALTER TABLE public.movimientos OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 33119)
-- Name: movimientos_id_movimiento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimientos ALTER COLUMN id_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_id_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4916 (class 0 OID 33104)
-- Dependencies: 220
-- Data for Name: cuentas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuentas (saldo_actual, saldo_inicial, id_cliente, id_cuenta, numero_cuenta, tipo_cuenta, nombre_cliente, estado_cuenta) FROM stdin;
\.


--
-- TOC entry 4918 (class 0 OID 33120)
-- Dependencies: 222
-- Data for Name: movimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimientos (saldo, valor, cuenta_id, fecha_movimiento, id_cliente, id_movimiento, tipo_movimiento, nombre_cliente) FROM stdin;
\.


--
-- TOC entry 4924 (class 0 OID 0)
-- Dependencies: 219
-- Name: cuentas_id_cuenta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuentas_id_cuenta_seq', 1, false);


--
-- TOC entry 4925 (class 0 OID 0)
-- Dependencies: 221
-- Name: movimientos_id_movimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimientos_id_movimiento_seq', 1, false);


--
-- TOC entry 4762 (class 2606 OID 33118)
-- Name: cuentas cuentas_numero_cuenta_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT cuentas_numero_cuenta_key UNIQUE (numero_cuenta);


--
-- TOC entry 4764 (class 2606 OID 33116)
-- Name: cuentas cuentas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT cuentas_pkey PRIMARY KEY (id_cuenta);


--
-- TOC entry 4766 (class 2606 OID 33128)
-- Name: movimientos movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_pkey PRIMARY KEY (id_movimiento);


--
-- TOC entry 4767 (class 2606 OID 33129)
-- Name: movimientos fk4moe88hxuohcysas5h70mdc09; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT fk4moe88hxuohcysas5h70mdc09 FOREIGN KEY (cuenta_id) REFERENCES public.cuentas(id_cuenta);


-- Completed on 2026-01-30 13:40:06

--
-- PostgreSQL database dump complete
--

\unrestrict Di57OhKhQslh7jJBslK0HgA7ZZHui2rigRbzZqW5N0jbewtEyZfp63RrorpF6jW

